defaults: &defaults
  locations_url: https://bibdata.princeton.edu/locations/digital_locations.json
  notifier_email_address: plum@princeton.edu
  iiif_url: <%= ENV["PLUM_IIIF_URL"] || "http://192.168.99.100:5004" %>
  file_url_module: LocalFileUrlGenerator
  jp2_recipes:
    default_color: >
      -rate 2.4,1.48331273,.91673033,.56657224,.35016049,.21641118,.13374944,.08266171 
      -jp2_space sRGB 
      -double_buffering 10 
      -num_threads 1 
      -no_weights 
      Clevels=6 
      Clayers=8 
      Cblk=\{64,64\} 
      Cuse_sop=yes 
      Cuse_eph=yes  
      Corder=RPCL 
      ORGgen_plt=yes 
      ORGtparts=R 
      Stiles=\{1024,1024\}
    default_gray: >
      -rate 2.4,1.48331273,.91673033,.56657224,.35016049,.21641118,.13374944,.08266171 
      -jp2_space sLUM 
      -double_buffering 10 
      -num_threads 1
      -no_weights 
      Clevels=6 
      Clayers=8 
      Cblk=\{64,64\} 
      Cuse_sop=yes 
      Cuse_eph=yes  
      Corder=RPCL 
      ORGgen_plt=yes 
      ORGtparts=R 
      Stiles=\{1024,1024\}
    geo_color: >
      -no_palette
      -rate 2.4,1.48331273,.91673033,.56657224,.35016049,.21641118,.13374944,.08266171 
      -jp2_space sRGB 
      -double_buffering 10 
      -num_threads 1 
      -no_weights 
      Clevels=6 
      Clayers=8 
      Cblk=\{64,64\} 
      Cuse_sop=yes 
      Cuse_eph=yes  
      Corder=RPCL 
      ORGgen_plt=yes 
      ORGtparts=R 
      Stiles=\{1024,1024\}
    geo_gray: >
      -no_palette
      -rate 2.4,1.48331273,.91673033,.56657224,.35016049,.21641118,.13374944,.08266171 
      -jp2_space sLUM 
      -double_buffering 10 
      -num_threads 1
      -no_weights 
      Clevels=6 
      Clayers=8 
      Cblk=\{64,64\} 
      Cuse_sop=yes 
      Cuse_eph=yes  
      Corder=RPCL 
      ORGgen_plt=yes 
      ORGtparts=R 
      Stiles=\{1024,1024\}
  events:
    server: 'amqp://localhost:5672'
    exchange: 'plum_events'
  geo_derivatives_path: <%= File.join(Rails.root, 'tmp', 'geo-derivatives') %>
  geoblacklight_provenance: 'Princeton'
  pulfa:
    master_files: <%= File.join(Rails.root, 'tmp', 'pulfa-master') %>
    service_files: <%= File.join(Rails.root, 'tmp', 'pulfa-service') %>

development:
  <<: *defaults

test:
  <<: *defaults
  pulfa:
    master_files: <%= File.join(Rails.root, 'spec', 'fixtures', 'files') %>
    service_files: <%= File.join(Rails.root, 'spec', 'fixtures', 'files') %>

production:
  <<: *defaults
  file_url_module: ExternalFileUrlGenerator
  external_file_url: "http://plum.princeton.edu:9090"
  events:
    server: <%= ENV['PLUM_RABBIT_SERVER'] || 'amqp://localhost:5672' %>
    exchange: "plum_events"

staging:
  <<: *defaults
  file_url_module: ExternalFileUrlGenerator
  external_file_url: "http://localhost:9000"
  events:
    server: <%= ENV['PLUM_RABBIT_SERVER'] || 'amqp://localhost:5672' %>
    exchange: "plum_events"
