defaults: &defaults
  events:
    server: <%= ENV['PLUM_RABBIT_SERVER'] || 'amqp://localhost:5672' %>
    exchange:
      geoblacklight: 'gbl_events'
      geoserver: 'geoserver_events'

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
